site_name: theSTART
site_url: https://joaopef.github.io/theSTART/

nav:
  - Home: index.md
  - Guides:
      - Pwnzilla: PwnZilla Guia.md
      - Pwnzilla INFO: 1HOW_IT_WORKS.md
      - Self-Hosted Password Manager: Password Manager.md
      - Air Monitor: Air Monitor.md

theme:
  name: material
  home_url: /theSTART/
  favicon: images/lightning.svg
  logo: images/lightning.svg
  features:
    - header.autohide
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/joaopef/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/joaopefer/
  analytics:
    provider: google
    property: G-4XTYJFCX0T

plugins:
  - search
  - i18n:
      reconfigure_material: true
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true
          link: /
        - locale: pt
          name: Português (PT)
          build: true
          link: /pt/

extra_javascript:
  - https://www.googletagmanager.com/gtag/js?id=G-4XTYJFCX0T

extra_css:
  - styles.css

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

copyright: 
  "&copy; 2025 <a href='https://github.com/joaopef/' target='_blank' rel='noopener'>João Ferreira</a>"

